[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_port  = COM4          ; CH343 USB-to-UART (no CP2102)

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0   ; serial vía CH343 UART (puerto izquierdo)

upload_port   = COM4          ; descomentar si PlatformIO no detecta el puerto
